### ISSUE TITLE
This is not correct. Forgetting a bind in the class Item user() method 

### ISSUE THREAD

**Issue by bmcilhenny** [learn-co-curriculum/js-object-oriented-object-relations-methods-readme#4]
class Item {
  constructor(name, price, user){
    this.id = ++itemId
    this.name = name
    this.price = price
    if(user){
      this.userId = user.id
    }
 
    // insert in the item to the store
    store.items.push(this)
  }
  setUser(user){
    this.userId = user.id
  }
  user(){
    return store.users.find(function(user){
      return user.id === this.userId
    }**(NEED A bind.(this) HERE )**
  }
}
 
let user = new User('Freddie')
let item = new Item('socks', 3, user)
item.user()
// {id: 3, name: 'Freddie'}

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @bmcilhenny.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
