### ISSUE TITLE
Need to add .bind() method to have access to this

### ISSUE THREAD

**Issue by robert-laws** [learn-co-curriculum/js-object-oriented-object-relations-methods-readme#5]
In the Item class, the user() method needs to have the .bind(this) method appended to have access to this within the callback function. Otherwise, it seems that this is undefined within the callback function. I think possibly an arrow function was intended to be used for the Item.user() method, similar to that used for the User.items() method.

```
// adding .bind(this) get the method to work properly
user() {
   return store.users.find(function(user){
      return user.id === this.userId
   }.bind(this))
}
```

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @robert-laws.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
