### ISSUE TITLE
changes on items() and user() methods to address "this" issues

### ISSUE THREAD

**Issue by IngridWong0715** [learn-co-curriculum/js-object-oriented-object-relations-methods-readme#6]
FIRST ISSUE: for items()
Original snippet
 ```
class User {
...
items(){
    return store.items.filter(item => {
      return item.userId === this.id
    })
  }
}
```
the `item =>` syntax causes confusion because we haven't learned it, and also because I can't tell how it addresses the issue of calling `this` from a callback. So change to : 
```
items(){
    return store.items.filter( function(item){
      return item.userId === this.id;
    }.bind(this));
  }
```

SECOND ISSUE: for user()
need to add `.bind(this)`
So like this: 
```
 user(){
    return store.users.find(function(user){
      return user.id === this.userId
    }.bind(this));
  }
```

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @IngridWong0715.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
