### ISSUE TITLE
Unclarity, in test/indexTest.js, line 156

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-object-oriented-object-relations-methods-readme#7]
describe('driver', function(){
    it('has a trips', function() {
      expect(driver.trips()).to.include(firstTrip)
      expect(driver.trips()).to.include(secondTrip)
    })

-- can this become more clear, either has trips, or has a trip?  Since a driver has many trips, it would be trips, delete the "a", I think. 

Same on line 158.

**Comment by maxwellbenton** [comment]
Thank you for providing this feedback, @MiriamPeskowitz.

We have documented this as a known issue and will be updating the js-object-oriented-class-relations-lab and this section in an upcoming update.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
