### ISSUE TITLE
Snippits for item class not using setUser()

### ISSUE THREAD

**Issue by cdcardle** [learn-co-curriculum/js-object-oriented-object-relations-methods-readme#9]
The snippits of the items class have a setUser() method that should be used above where it is defined, but instead the code inside setUser() is used.  `if (user) {this.userId = user.id;}` instead of `if (user) {this.setUser(user)}`

**Comment by sgharms** [comment]
Good point. This method is used in the previous lesson. Nevertheless, it doesn't seem very essential to this lesson. We'll set this as a known issue and work out both of those in a subsequent upgrade.
Thanks for the information.
